---
version: '3.9'
services:
  web:
    build: ./frontend
    ports:
      - 5173:5173
  api:
    build: ./backend
    command: 
    ports:
      - 8000:8000
    environment:
      - ALLOWED_HOSTS=localhost, 127.0.0.1